### ISSUE TITLE
Naming of MessageId property In SendResponse and parameter in GetMessageDetailsAsync() seems inconsistent

### ISSUE THREAD

**Issue by jbennink** [mDev86/PostalApiClient#1]
The SendMessageAsync() returns a SendResponse that has a MessageId property of type string. 

The GetMessageDetailsAsync() call requires a MessageId parameter, but that is of type int. It seems the Id required by this method is in the MessageInfo that is found in the Messages dictionary.  

Since the SendResponse can contain multiple messages wouldn't the MessageId be more a ResponseId, of even just Id.
What is the use of this property, it seems to contain a guid@mailerdomain (like 4b18d3bc-fc2d-4062-bcab-7bf05dc7249c@rp.remails.net in my case)

**Comment by mDev86** [comment]
@jbennink as I understand it, the Postal Server really contains two different type for message identifier.
1. MessageId from SendResponse (string with guid@domain) insert as header ('message-id') in email and have name in ui as "Message ID"

![изображение](https://github.com/mDev86/PostalApiClient/assets/16636157/760ad2a3-51e9-4845-9679-aa239009752f)
 
![изображение](https://github.com/mDev86/PostalApiClient/assets/16636157/83d9dd86-7a9c-4a7f-944d-7d04f1c4a60f)


2. Id in MessageInfo (integer) use as internal ID message in Postal database. Exactly this property necessary for api methods GetMessage*Async()

Such naming using in official docs [see response Sending a message](https://docs.postalserver.io/developer/api#sending-a-message) and [description for parameter id](https://apiv1.postalserver.io/controllers/messages/message.html)
