### ISSUE TITLE
Consider using ErrorOr or OneOf types instead of returning tuples

### ISSUE THREAD

**Issue by jbennink** [mDev86/PostalApiClient#2]
With ErrorOr the SendMessageAsync would become:

public async Task<ErrorOr<SendResponse>> SendMessageAsync(PostalMessage requestModel)

and would be used like:
```c#
var result = await _postalApiClient.SendMessageAsync(message);

if(result.IsError) Console.WriteLine(result.FirstError.Description);

Console.WriteLine(result.Value.MessageId); // Value is the SendResponse type
```

ErrorOr: https://github.com/amantinband/error-or
OneOf: https://github.com/mcintyre321/OneOf

I use ErrorOr because it fits my need better, but I OneOf has been around longer and allows you to return multiple types. Since I use this mostly to return the thing, or an error I feel like ErrorOr suits my needs better.

**Comment by mDev86** [comment]
@jbennink thanks for recommendation. I looked at OneOf and I liked this approach
